- name: install required selinux tools
  yum:
    name: policycoreutils-python-utils
    state: present
- name: set permissions
  file:
    path: /var/ftp/pub
    mode: '0777'
- name: set selinux boolean
  seboolean:
    name: ftpd_anon_write
    state: yes
    persistent: yes
- name: manage selinux settings
  sefcontext:
    target: /var/ftp/pub
    setype: public_content_rw_t
    state: present
  notify:
    - run restorecon
