---
- name: Exercise 6-3
  hosts: ansible1
  become: true
  vars_files:
    - vars/secrets.yaml

  tasks:
    - name: Create user
      user:
        name: "{{ username }}"
        password: "{{ pwhash }}"
