---
- name: Exercise 13-3
  hosts: ansible1
  become: true

  tasks:
    - name: Create groups
      group:
        name: "{{ item.groups }}"
        state: present
      loop: "{{ users }}"
    - name: Create users
      user:
        name: "{{ item.username }}"
        state: present
        groups: "{{ item.groups }}"
        append: true
      loop: "{{ users }}"
    - name: Allow group members in sudo
      template:
        src: templates/sudoer.j2
        dest: /etc/sudoers.d/sudogroups
        validate: 'visudo -cf %s'
        mode: 0440
      loop: "{{ users }}"

