---
- name: Manage SELinux policy example
  hosts: ansible1
  become: true

  vars:
    # Use "targeted" SELinux policy type
    selinux_policy: targeted
    # Set "enforcing" mode
    selinux_state: enforcing
    # Switch some SELinux booleans
    selinux_booleans:
      - name: cron_can_relabel
        state: true
        persistent: true
    # SELinux file type
    selinux_fcontexts:
      - target: '/var/ftp/uploads(/.*)?'
        setype: public_content_rw_t
        ftype: d
        state: present
    # Restore SELinux file contexts in '/tmp/test_dir'
    selinux_restore_dirs:
      - /var/ftp/uploads
    # Map tcp port 22100 to the 'ssh_port_t' SELinux port type
    selinux_ports:
      - ports: 82
        proto: tcp
        setype: ssh_port_t
        state: present

  tasks:
    - name: Creates directory
      file:
        path: /var/ftp/uploads
        state: directory
        mode: "777"

    - name: Execute the role and reboot in a rescue block
      block:
        - name: Include selinux role
          include_role:
            name: rhel-system-roles.selinux
      rescue:
        - name: >-
            Fail if failed for a different reason than selinux_reboot_required
          fail:
            msg: "role failed"
          when: not selinux_reboot_required

        - name: Restart managed host
          reboot:

        - name: Wait for managed host to come back
          wait_for_connection:
            delay: 10
            timeout: 300

        - name: Reapply the role
          include_role:
            name: rhel-system-roles.selinux
