---
- name: Exercise 12-1
  hosts: ansible2
  become: true
  vars:
    my_package: nano

  tasks:
    - name: Install {{ my_package }}
      dnf:
        name: "{{ my_package }}"
        state: latest
    - name: Update package facts
      package_facts:
    - name: Show package facts for {{ my_package }}
      debug:
        var: ansible_facts['packages'][my_package]
      when: my_package in ansible_facts['packages']
