---
- name: Example with multiple servers
  become: true
  hosts: 
    - ansible1
    - ansible2
  vars:
    timezone: UTC
    timesync_ntp_servers:
      - hostname: pool.ntp.org
        iburst: true

  roles:
    - rhel-system-roles.timesync
  tasks:
    - name: Configure timezone
      timezone:
        name: "{{ timezone }}"
