---
- name: Install and start the web service
  hosts: ansible1
  become: true

  tasks:
    - name: Install the package
      yum:
        name: "{{ ansible_facts['ansible_local']['custom']['software']['package'] }}"
    - name: Start and enable the service
      service:
        name: "{{ ansible_facts['ansible_local']['custom']['software']['service'] }}"
        state: "{{ ansible_facts['ansible_local']['custom']['software']['state'] }}"
        enabled: "{{ ansible_facts['ansible_local']['custom']['software']['enabled'] }}"
