---
- hosts: ansible1

  tasks:
    - name: Copy multiline text
      copy:
        content: |
          line 1
          line 2
        dest: /tmp/multiline1.txt
    - name: Copy more text
      copy:
        content: >
          line 1
          line 2
        dest: /tmp/multiline2.txt
    - name: Cleanup files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/multiline1.txt
        - /tmp/multiline2.txt

